name: AWS S3 LS Command

on:
  push:
    branches:
      - main

jobs:
  aws_s3_ls:
    runs-on: ubuntu-latest
    
    steps:
    - name: Set up AWS CLI
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
        aws-region: eu-central-1  # Set your AWS region here
      

    - name: Run AWS S3 LS
      run: aws s3 ls
