name: AWS S3 LS Command

on:
  push:
    branches:
      - main  # Du kannst auch andere Branches hier angeben, je nach Bedarf
env:
  BUCKET_NAME: techstarter-93358

jobs:
  aws-s3-ls:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up AWS CLI
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
        aws-region: eu-central-1
        # aws-session-token: xxx
      
    - name: upload to S3
      run: aws s3 cp ./website s3://$BUCKET_NAME/ --recursive

        
